name: CI

on:
  schedule:
    - cron: "0 * * * *"
  #push:
   #  branches:
   #   - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.*

      - name: Build presets.xml
        run: dotnet run PresetsGenerator.csproj

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: presets.xml
          asset_name: presets.xml
          tag: release-${{ github.ref }}
          overwrite: true
